### PR TITLE
IMPROVED index.html

### PR DESCRIPTION
**Pull request by shahriar-azad-evan-github-io**
I think this is better it was in my book.

### CODE REVIEW

**Comment by irhamdz** [comment]
can u add #80 to this PR as well?

**Comment by shahriar-azad-evan-github-io** [comment]
> can u add #80 to this PR as well?

Bro can you please explain me thing. I am not too much techy person . But i will try my best .

**Comment by irhamdz** [comment]
> > can u add #80 to this PR as well?
> 
> Bro can you please explain me thing. I am not too much techy person . But i will try my best .

in #80 u only add 'one' text, it better just to add that change to this PR but with a different commit, and change the PR title to improved index.html and readme.md

**Comment by shahriar-azad-evan-github-io** [comment]
> > > can u add #80 to this PR as well?
> > 
> > 
> > Bro can you please explain me thing. I am not too much techy person . But i will try my best .
> 
> in #80 u only add 'one' text, it better just to add that change to this PR but with a different commit, and change the PR title to improved index.html and readme.md

Done both 🤠 . Please accept now .

**Pull request merged**
